//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4_Variant_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Агенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Агенты()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int ID_Агента { get; set; }
        public string Наименование_компании { get; set; }
        public string Тип_агента { get; set; }
        public string Юридический_адрес { get; set; }
        public Nullable<int> ИНН { get; set; }
        public string КПП { get; set; }
        public string ФИО_директора { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string Email { get; set; }
        public byte[] Логотип { get; set; }
        public string Приоритетность_в_поставках { get; set; }
        public string Точки_продаж { get; set; }
        public string История_реализации_продукции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
    }
}
