//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4_Variant_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияИзмКолМатериала
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> ID_Материала { get; set; }
        public Nullable<int> Новое_Количество { get; set; }
    
        public virtual Материал Материал { get; set; }
    }
}
