//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4_Variant_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        public int ID_Поставщика { get; set; }
        public string Наименование_поставщика { get; set; }
        public string Тип_поставщика { get; set; }
        public Nullable<long> ИНН { get; set; }
        public Nullable<int> Рейтинг_качества { get; set; }
        public Nullable<System.DateTime> Дата_начала_работы_с_поставщиком { get; set; }
    }
}
